baseurl = "http://mafinar.ca/"
title = "mafinar's website"
theme = "vienna"
languageCode = "en-us"
copyright = "&copy; Copyright 2018 Mafinar K."

[params]
  bgcolor = "#34495e"
  subtitle = "Mafinar writes about things he plays with"
  author = "Mafinar Khan"
  bio = "Pythonista.Djangonaut.Alchemist"
  twitter = "mafinar"
  facebook = "mafinar"
  angellist = "mafinar-khan"
  medium = "mafinar"
  reddit = "code-shoily"
  linkedin = "mafinar-khan"
  youtube = "mafinar"
  github = "code-shoily"
  ga_api_key = "UA-112774615-1"
  disqusShortname = "codeshoily"
  contact = "mafinar@gmail.com"
  themecolor = "#34495e"
