baseurl = "http://mafinar.ca/"
title = "learn ▷ play ▷ write"
theme = "vienna"
languageCode = "en-us"
DefaultContentLanguage = "en"
copyright = "&copy; Copyright 2018 Mafinar K."
publishDir = "docs"
disqusShortname = "mafinar-dot-ca"

[params]
  bgcolor = "#34495e"
  subtitle = "<a class='about-link' href='/pages/about/'>Mafinar</a> writes about <strike>Elixir and Python</strike> things"
  author = "Mafinar Khan"
  bio = "Pythonista.Djangonaut.Alchemist"
  twitter = "mafinar"
  facebook = "mafinar"
  angellist = "mafinar-khan"
  reddit = "code-shoily"
  linkedin = "mafinar-khan"
  youtube = "mafinar"
  github = "code-shoily"
  ga_api_key = "UA-112774615-1"
  contact = "mafinar@gmail.com"
  themecolor = "#34495e"

[taxonomies]
  pages = "pages"
  tag = "tags"

[languages]
  [languages.en]
    weight = 1

  [languages.bn]
    weight = 2